name: CI
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/checkout@v2
      - name: get modules
        run: yarn
        
      - name: Cypress run on Firefox
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
      
      - name: tests
        run: yarn test:e2e:ci
