name: CI
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/checkout@v2
      - name: get modules
        run: yarn
        
      - name: Tests
        run: yarn build && yarn test:e2e:ci
